version: '3'

services:
  postgres-database:
    image: postgres:13.12
    ports:
      - 5432:5432
    env_file:
      - docker.env
    networks:
      - postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - docker.env
    ports:
      - 3000:3000
    depends_on:
      - postgres-database
    volumes:
      - ./src:/app/src
    networks:
      - postgres

  adminer:
    image: dockette/adminer:full-php5
    ports:
      - 8080:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
